# Generated by Django 5.2 on 2025-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rssfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='category',
            field=models.CharField(blank=True, help_text="The default category for articles from this feed (e.g., 'World', 'Sports').", max_length=100),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='source_name',
            field=models.CharField(blank=True, help_text="The name of the source (e.g., 'The Hindu'). If blank, it will try to fetch from the feed.", max_length=255),
        ),
    ]
