# Generated by Django 5.2 on 2025-05-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sha256_hash',
        ),
    ]
