# Generated by Django 5.2 on 2025-05-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_sha256_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the feed (e.g., 'The Hindu National')", max_length=255, unique=True)),
                ('url', models.URLField(help_text='URL of the RSS feed', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this feed should be processed')),
            ],
        ),
    ]
